### ISSUE TITLE
Challenges building while following instructions in readme (false alarms, but leaving this for others)

### ISSUE THREAD

**Issue by arrowtype** [mfeq/Qglif#16]
Context: I’m on macOS 10.15.5 and I wanted to install this to try it out. I had a few hurdles in doing so, and I’ve figured them out but will leave this issue (and close it) in case it helps others who have the same issues.

I was curious to check this out, but after following the directions to install vulkanSDK & rustup, the build was stopped at an error:

```console
   Compiling glifparser v0.0.0 (https://github.com/mfeq/glifparser#e3c77586)
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> /Users/stephennixon/.cargo/git/checkouts/glifparser-a0b09305bd94eda1/e3c7758/src/lib.rs:1:1
  |
1 | #![feature(assoc_char_funcs, let_chains)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

   Compiling aho-corasick v0.7.13
error: aborting due to previous error

For more information about this error, try `rustc --explain E0554`.
error: could not compile `glifparser`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

So, I ran `rustc --explain E0554` as suggested, and realized that I _hadn’t_ quite followed all the instructions – I hadn’t configured the rust installation to use the `nightly` toolchain. 

So, I ran the build again, and ... I got another error:

```console
   Compiling skulpin v0.10.0
   Compiling Qglif v0.1.0 (/Users/stephennixon/code/Qglif)
    Finished dev [unoptimized + debuginfo] target(s) in 52.55s
     Running `target/debug/Qglif Q_.glif`
[2020-09-13T01:33:18Z DEBUG Qglif::io] Loaded "Q" (U+0051) from Q_.glif
[2020-09-13T01:33:18Z DEBUG Qglif::imgui::support] Building ImGui font atlas
[2020-09-13T01:33:18Z INFO  skulpin_renderer::instance] Finding vulkan entry point
Error during renderer construction: CreateInstanceError(LoadingError(LoadingError(DlOpen { desc: "dlopen(libvulkan.dylib, 2): image not found" })))
```

I found that this is because I misunderstood the vulkanSDK [Getting Started](https://vulkan.lunarg.com/doc/sdk/1.2.148.1/mac/getting_started.html) guide. I tried to do the main method of moving the DMG files into a folder within my home directory. However, I had to also do their "Alternate method" of running the `./install_vulkan.py` script.

With this, the build worked!

![image](https://user-images.githubusercontent.com/45946693/93008245-8f5a6700-f540-11ea-92b5-60542e678890.png)

Qool! (Dumb joke, sorry.) Looking forward to playing with this a bit. Thanks for making this pretty straightforward for newcomers to build!

**Comment by bghryct** [comment]
Interestingly I'm on MacOS 10.15.6 and I've run into different issues.
( Tried building on 10.15.5 as well and the same issues arose) 
Might be my general ignorance with Rust, but I followed the instructions, and made sure to install Rust using the nightly toolchain. Placed Vulkan in home and ran ```install_vulkan.py``` as noted by @arrowtype. Finding it odd that I got completely different problems. But again, probably my ignorance with Rust. 

Running the build I get these two errors;

```
error[E0432]: unresolved import `std::fs::unix`
  --> /Users/MirkoVelimirovic/.cargo/git/checkouts/ipc-cd6c26597b8d65e9/b325f9a/src/lib.rs:92:46
   |
92 | ...                   use std::fs::unix::PermissionsExt;
   |                                    ^^^^ could not find `unix` in `fs`

error[E0599]: no method named `mode` found for struct `Permissions` in the current scope
  --> /Users/MirkoVelimirovic/.cargo/git/checkouts/ipc-cd6c26597b8d65e9/b325f9a/src/lib.rs:93:53
   |
93 | ...                   if md.permissions().mode() & 0o111 != 0 {
   |                                           ^^^^ method not found in `Permissions`
   |
   = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
   |
4  | use std::os::unix::fs::PermissionsExt;
   |

error: aborting due to 2 previous errors

Some errors have detailed explanations: E0432, E0599.
For more information about an error, try `rustc --explain E0432`.
error: could not compile `mfeq-ipc`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed


```

**Comment by ctrlcctrlv** [comment]
Ah ha. The IPC stuff doesn't compile, oops. It should be `use std::os::unix::fs::PermissionsExt;` not whatever I wrote. I should be able to easily fix that.

**Comment by bghryct** [comment]
Cool. I got it to run by ripping out the offending line. Not very graceful, but it compiled!

![119234646_324281712187007_1746399699883219364_n](https://user-images.githubusercontent.com/3279863/93027644-42c46980-f5dc-11ea-8d18-e33f3d578f39.png)

**Comment by bghryct** [comment]
btw @ctrlcctrlv tested your fix, and it builds as well.

**Comment by ctrlcctrlv** [comment]
Great news. I'm glad I took the time to make it work on Mac and document the process, as it seems I underestimated how popular Macs are. I make my fonts on Linux usually, Windows sometimes.

**Comment by bghryct** [comment]
I feel like on a purely /political?/ level to make a font editor truly successful you'll need to convince a lot of mac users to switch. part of that bridge is education, part of that bridge is making it easier for them. I use a mac still because of the stranglehold on graphic design apple has. Basically I need to be able to work with other glyphs and robofont users and I can't do that (currently) if I go full linux. I really appreciate you working on this, and I've got real hope that "this time is different" 

Appreciated reading the documentation on the build philosophy you've put together. I'm still rolling it around in my skull, but I'll try and come up with halfway intelligent feedback here and there.
